name: Deploy to Expo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm uninstall -g @expo/eas-cli
          npm install -g @expo/eas-cli
      - name: Login to Expo
        run: npx expo login -u Zero0ne -p User#153789
      - name: Publish to Expo
        run: npx eas update
