name: Deploy to Expo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Login to Expo
      run: npx expo login -u ZeroOne -p User#153789
    - name: Publish to Expo
      run: CI=true npx expo publish
